from listas import LinkedList

l = LinkedList()
print(f"L esta vacia? {l.is_empty()}")
l.append(10)
l.append(5)
l.append(6)
l.append(20)
print(f"L esta vacia? {l.is_empty()}")
l.transversal()
l.remove(10)
l.transversal()
l.preppend(3)
l.transversal()
x=l.tail()
print(x.data)
print(l.get())

print("")
print("")
print("Tarea get")
print(l.get(3))
print(l.get(5))
print(l.get(6))
print(l.get())
print(l.get(20))
print(l.get(22))
print(l.get(100))

